# Generated by Django 3.2.4 on 2021-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsdata',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
